name: tests unitaires

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Vous pouvez spécifier une autre version si nécessaire

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run tests
        run: |
          pytest TP1/test.py

      - name: Display branch name
        run: echo "Nom branche : ${{ github.ref }}"

      - name: Display OS version
        run: echo "OS version : ${{ runner.os }}"

